# -*- coding: utf-8 -*-
"""FinalProject_TSA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1luk8eMsJCgZcnNatK_mraxu02vKECn_w

## Forecasting ESG impact on Stock Prices

### Phase 1: Data Loading & Company Selection
1. Load the CSV and print basic info (shape, columns, dtype).
2. Identify ESG-like columns (Company_ESG_pulse, ESG_beta, Sustainalytics, etc.).
3. Confirm whether ESG is time-varying (we expect static for this dataset).
4. Compute company-level average ESG and rank companies.
5. Select three representative companies (low, median, high).
6. Save the selection for later phases.
"""

# Load the Dataset
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from pandas.tseries.offsets import BDay
import yfinance as yf
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("/content/drive/MyDrive/TSA/Industrials-sector-ESG-and-stock-market-data.csv")
df.head()

# Explore the Dataset
print(df.info())
print("\nColumns:", df.columns.tolist())
print("\nMissing Value Percentage:")
print(df.isna().mean().sort_values(ascending=False))

print("\nNumber of Companies:", df['Company_name'].nunique())

# Rank Companies by their ESG Score
avg_esg = df.groupby('Company_name')['Company_ESG_pulse'].mean().sort_values()
avg_esg

# Select High, Medium, and Low ESG Companies
low_esg_company = avg_esg.index[0]
mid_esg_company = avg_esg.index[len(avg_esg)//2]
high_esg_company = avg_esg.index[-1]

selected_companies = [low_esg_company, mid_esg_company, high_esg_company]
selected_companies

# Save the Selected Companies
import os
os.makedirs("results", exist_ok=True)

with open("results/selected_companies.txt", "w") as f:
    for c in selected_companies:
        f.write(c + "\n")

"""### Phase 2: Cleaning & Time Alignment
1. Load the selected companies from Phase 1.
2. Download daily stock prices using `yfinance`.
3. Reindex each series to continuous Business-Day frequency.
4. Forward-fill missing price values.
5. Attach static ESG value to every row for that company.
6. Compute time-series features:
   - log-price
   - daily log-return
   - 7-day rolling volatility
   - 30-day rolling volatility
7. Store cleaned DataFrames in a dictionary (`cleaned_data`) for later phases.

This results in a clean, aligned, daily-frequency dataset for ARIMA, VAR, and LSTM models.
"""

# Identify ESG & Symbol columns
company_col = "Company_name"
symbol_col  = "Symbol"
esg_col     = "Company_ESG_pulse"

print("Using columns:")
print(" Company =", company_col)
print(" Symbol  =", symbol_col)
print(" ESG     =", esg_col)

# Map each selected company to its ESG score (static)
company_esg_map = {}

for comp in selected_companies:
    esg_vals = df.loc[df[company_col] == comp, esg_col].dropna().astype(float)
    if len(esg_vals) == 0:
        company_esg_map[comp] = np.nan
    else:
        company_esg_map[comp] = float(esg_vals.mean())

company_esg_map

def download_daily_prices(ticker, start="2018-01-01"):
    """
    Downloads daily price data for a given ticker.
    Returns a DataFrame with close and volume.
    """
    try:
        data = yf.download(ticker, start=start, progress=False)
        if data.empty:
            return pd.DataFrame()
        dfp = data[['Close', 'Volume']].rename(columns={'Close':'close','Volume':'volume'})
        dfp.index = pd.to_datetime(dfp.index)
        return dfp
    except Exception as e:
        print("Error downloading", ticker, ":", e)
        return pd.DataFrame()

cleaned_data = {}

for comp in selected_companies:
    print(f"\nProcessing: {comp}")

    ticker = df.loc[df[company_col] == comp, symbol_col].dropna().unique()
    if len(ticker) == 0:
        print(" No ticker found — skipping.")
        continue

    ticker = ticker[0]  # use first unique ticker
    print(" Ticker =", ticker)

    # Download price history
    price_df = download_daily_prices(ticker)

    if price_df.empty:
        print(" Price download failed for", comp)
        continue

    # Reindex to business days
    full_idx = pd.date_range(start=price_df.index.min(),
                             end=price_df.index.max(),
                             freq=BDay())
    price_df = price_df.reindex(full_idx).ffill()

    # Add ESG (static)
    price_df['ESG'] = company_esg_map[comp]

    # Compute features
    price_df['log_price'] = np.log(price_df['close'])
    price_df['return'] = price_df['log_price'].diff()
    price_df['volatility_7d'] = price_df['return'].rolling(7).std()
    price_df['volatility_30d'] = price_df['return'].rolling(30).std()

    cleaned_data[comp] = price_df

    print(f" Completed: {comp} — {len(price_df)} daily rows")

summary = []

for comp, dfc in cleaned_data.items():
    summary.append({
        'Company': comp,
        'Rows': len(dfc),
        'Non-null returns': dfc['return'].notna().sum(),
        'ESG value': dfc['ESG'].iloc[0]
    })

summary_df = pd.DataFrame(summary)
summary_df

"""### Phase 3: Exploratory Data Analysis (EDA)

This phase performs a thorough visual and statistical exploratory analysis for each selected company in `cleaned_data`.  
For every ticker we will produce:

- Quick numeric summary of key columns
- Price and daily-return plots
- Rolling volatility plot with ESG overlay (if available)
- ACF and PACF plots for returns
- STL decomposition of the price series (seasonal/trend/resid)
- Stationarity tests: Augmented Dickey–Fuller (ADF) and KPSS
- Correlation heatmap of engineered features (returns, volatility, lagged returns, etc.)

Notes:
- ESG is static for our dataset; its plot will often appear as a flat line. We still display it to document the data limitation.
- Plots are shown inline and diagnostic statistics are printed in concise format for interpretation.

"""

# Phase 3 — imports and helpers
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import acf, pacf, adfuller, kpss
from statsmodels.tsa.seasonal import STL
import seaborn as sns  # only for dataframe heatmap convenience (we won't use seaborn styling)

# adjust matplotlib defaults for readable plots
plt.rcParams['figure.figsize'] = (10,4)
plt.rcParams['lines.linewidth'] = 1.25
plt.rcParams['axes.grid'] = True

def show_summary(df, ticker):
    print(f"=== Summary for {ticker} ===")
    display(df[['close','ESG','return']].describe().T)
    print("\nNull counts:")
    print(df[['close','ESG','return']].isna().sum())

def safe_series(df, col):
    return df[col] if col in df.columns else pd.Series(dtype=float, index=df.index)

# list available tickers
print("Available tickers in cleaned_data:", list(cleaned_data.keys()))

for tkr, dfc in cleaned_data.items():
    show_summary(dfc, tkr)
    print("\n---\n")

# Price & Return plots
for tkr, dfc in cleaned_data.items():
    fig, axes = plt.subplots(2,1, figsize=(12,8), sharex=True)
    axes[0].plot(dfc.index, dfc['close'])
    axes[0].set_title(f"{tkr} — Close Price")
    axes[0].set_ylabel("Price")
    axes[1].plot(dfc.index, dfc['return'])
    axes[1].set_title(f"{tkr} — Daily Log Returns")
    axes[1].set_ylabel("Return")
    plt.tight_layout()
    plt.show()

# Rolling volatility and ESG (overlay)
for tkr, dfc in cleaned_data.items():
    fig, ax = plt.subplots(2,1, figsize=(12,7), sharex=True)
    ax[0].plot(dfc.index, dfc['volatility_30d'])
    ax[0].set_title(f"{tkr} — 30-day rolling volatility (returns)")
    ax[0].set_ylabel("Volatility")
    ax[1].plot(dfc.index, dfc['ESG'])
    ax[1].set_title(f"{tkr} — ESG (static) over time")
    ax[1].set_ylabel("ESG")
    # draw horizontal line at ESG (single value) for clarity if constant
    if not dfc['ESG'].isna().all():
        esg_val = dfc['ESG'].dropna().iloc[0]
        ax[1].axhline(esg_val, linestyle='--')
    plt.tight_layout()
    plt.show()

# ACF and PACF for returns
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
for tkr, dfc in cleaned_data.items():
    series = dfc['log_price'].dropna()

    fig, axes = plt.subplots(1,2, figsize=(14,4))
    plot_acf(series, ax=axes[0], lags=40)
    axes[0].set_title(f"{tkr} — ACF (log price)")

    plot_pacf(series, ax=axes[1], lags=40, method='ywm')
    axes[1].set_title(f"{tkr} — PACF (log price)")

    plt.tight_layout()
    plt.show()

# STL decomposition of log_price
for tkr, dfc in cleaned_data.items():
    series = safe_series(dfc, 'log_price').dropna()
    if len(series) < 365:  # need enough data for seasonal decomposition
        print(f"{tkr}: not enough data for robust STL (n={len(series)}) — skipping.")
        continue
    stl = STL(series, period=252, robust=True)  # 252 trading days ~ 1 year
    res = stl.fit()
    fig = res.plot()
    fig.suptitle(f"{tkr} — STL decomposition (log_price)")
    plt.show()

# Stationarity tests: ADF and KPSS
import warnings
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.tools.sm_exceptions import InterpolationWarning

# Suppress unwanted warnings (KPSS interpolation + general warnings)
warnings.filterwarnings("ignore")
warnings.simplefilter("ignore", InterpolationWarning)

stationarity_results = []

for tkr, dfc in cleaned_data.items():
    ret = dfc['return'].dropna()

    # ADF
    adf_stat, adf_p, adf_lags, adf_obs, _, _ = adfuller(ret, autolag='AIC')

    # KPSS
    kpss_stat, kpss_p, kpss_lags, _ = kpss(ret, regression='c', nlags='auto')

    stationarity_results.append({
        "Symbol": tkr,
        "ADF_stat": round(adf_stat, 4),
        "ADF_pvalue": round(adf_p, 5),
        "ADF_lags": adf_lags,

        "KPSS_stat": round(kpss_stat, 4),
        "KPSS_pvalue": round(kpss_p, 5),
        "KPSS_lags": kpss_lags
    })

# Convert to a clean DataFrame
stationarity_df = pd.DataFrame(stationarity_results)
display(stationarity_df)

# Correlation heatmap of available features
for tkr, dfc in cleaned_data.items():
    numeric = dfc[['close','return','volatility_7d','volatility_30d']].copy()
    numeric = numeric.dropna(how='all')
    if numeric.shape[0] < 10:
        print(f"{tkr}: not enough data for correlation heatmap (n={numeric.shape[0]})")
        continue
    corr = numeric.corr()
    fig, ax = plt.subplots(figsize=(6,5))
    im = ax.imshow(corr, vmin=-1, vmax=1)
    ax.set_xticks(range(len(corr.columns))); ax.set_xticklabels(corr.columns, rotation=45, ha='right')
    ax.set_yticks(range(len(corr.index))); ax.set_yticklabels(corr.index)
    fig.colorbar(im, ax=ax)
    ax.set_title(f"{tkr} — Feature correlation")
    plt.tight_layout()
    plt.show()

"""### Phase 4: Feature Engineering

In this phase, we create additional variables from the cleaned time-series that will be useful
for exploratory analysis and forecasting models.

Since stock prices are non-stationary but returns behave like stationary white noise, we focus
on engineering features derived from returns and volatility:

#### Features created:
- **log_price** — Natural log of closing price (stabilizes variance)
- **return** — First difference of log_price (stationary transformation)
- **volatility_7d** — 7-day rolling standard deviation of returns
- **volatility_30d** — 30-day rolling standard deviation of returns
- **lagged returns (1, 2, 5 days)** — useful for ARIMA / ARIMAX models
- **squared return** — proxy for volatility clustering
- **absolute return** — often used in volatility modeling

Since ESG is static in our dataset, it is included as a **time-invariant exogenous feature**,
not a dynamic regressor.


"""

for tkr, dfc in cleaned_data.items():
    print(f"\n=== Feature Summary for {tkr} ===")
    display(dfc.describe()[[
        'return','return_lag1','return_lag2','return_lag5',
        'volatility_7d','volatility_30d','return_squared','abs_return'
    ]])

"""### Phase 5: Classical Time-Series Modelling

This phase fits and compares classical time-series models:

**A. Baseline**
1. Fit ARIMA on returns (no ESG).
2. Evaluate baseline (train/test RMSE, MAE).

**B. ESG-Augmented Models**

3. Fit ARIMAX (SARIMAX) using ESG as an exogenous (static) regressor.

4. Compare ARIMAX vs ARIMA.

**C. Multivariate Models**

5. Use VAR on multivariate *time-varying* series (returns + volatility) — ESG is static so excluded from VAR.

6. Compute impulse response functions (IRFs) for the VAR.

7. Run Granger causality tests between returns and volatility.
"""

# Imports and helpers
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error
import warnings
warnings.filterwarnings("ignore")

# statsmodels
import statsmodels.api as sm
from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import grangercausalitytests

plt.rcParams['figure.figsize'] = (10,4)

def train_test_split_series(series, h=252):
    """Return train, test (last h points as test)."""
    series = series.dropna()
    return series.iloc[:-h], series.iloc[-h:]

def evaluate_forecast(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    return {'MAE': mae, 'RMSE': rmse}

# A1. ARIMA & ARIMAX training + forecasting
import os, math, warnings
import numpy as np, pandas as pd
from pandas.tseries.offsets import BDay
from statsmodels.tsa.statespace.sarimax import SARIMAX

warnings.filterwarnings("ignore")

OUT_DIR = "results/phase5"
os.makedirs(OUT_DIR, exist_ok=True)

# small grid for ARIMA order (on returns which are usually stationary)
P_GRID = [0,1,2]
D = 0   # returns are typically stationary; keep d=0
Q_GRID = [0,1,2]

def safe_name(s):
    return s.replace(" ","_").replace("/","_")

def dm_test_from_errors(e1, e2):
    # squared-error DM for h=1
    from scipy import stats
    d = e1**2 - e2**2
    mean_d = d.mean()
    sd = d.std(ddof=1)
    T = len(d)
    denom = sd / math.sqrt(T) if sd>0 else np.nan
    dm = mean_d/denom if denom and denom>0 else np.nan
    p = 2*(1 - stats.norm.cdf(abs(dm))) if np.isfinite(dm) else np.nan
    return dm, p

if 'selected_companies' not in globals() or 'cleaned_data' not in globals():
    raise RuntimeError("selected_companies or cleaned_data missing. Run Phase 1/2 first.")

summary_records = []
for comp in selected_companies:
    print("\n=== Processing:", comp, "===")
    df = cleaned_data.get(comp)
    if df is None or not hasattr(df, 'columns'):
        print("  No data for", comp, "- skipping.")
        continue
    # ensure datetime index
    try:
        df.index = pd.to_datetime(df.index)
    except:
        pass
    df = df.sort_index()

    # require return column
    if 'return' not in df.columns or df['return'].dropna().shape[0] < 150:
        print("  Not enough return observations for", comp, "- skipping ARIMA/ARIMAX.")
        continue

    # prepare supervised series: use only rows with non-null return
    ret_ser = df['return'].astype(float).dropna()
    # create ESG lag-1 for ARIMAX if available
    esg_present = ('ESG' in df.columns) and (df['ESG'].notna().sum() > 1)
    if esg_present:
        df['ESG_lag1'] = df['ESG'].shift(1)
    else:
        df['ESG_lag1'] = np.nan

    # define train/test split by date: test = last 252 business-target days
    # Build sequences target dates same as Phase6: we already created predictions there, but here we emulate same split:
    last_date = df.index.max()
    test_start_date = last_date - BDay(252-1)
    # Align to days where return is present (target dates)
    ret_idx = ret_ser.index
    test_mask = ret_idx >= pd.to_datetime(test_start_date)
    if test_mask.sum() < 40:
        # fallback to last 252 samples
        test_size = min(252, len(ret_idx))
        test_mask = np.arange(len(ret_idx)) >= (len(ret_idx) - test_size)

    idx_all = np.arange(len(ret_idx))
    test_idx = idx_all[test_mask]
    pre_idx = idx_all[~test_mask]
    if len(pre_idx) < 60:
        print("  Insufficient pre-test samples for", comp, "- skipping.")
        continue

    # create train/val? For ARIMA we train on pretest (all) and evaluate on test, consistent with earlier pipeline
    train_idx = pre_idx
    test_idx_dates = ret_idx[test_idx]
    train_series = ret_ser.iloc[train_idx]
    test_series = ret_ser.loc[test_idx_dates]  # aligned by date

    # pick best ARIMA order by AIC
    best_aic = np.inf; best_order = None; best_model = None
    for p in P_GRID:
        for q in Q_GRID:
            try:
                mod = SARIMAX(train_series, order=(p,D,q), enforce_stationarity=False, enforce_invertible=False)
                res = mod.fit(disp=False, maxiter=50)
                aic = res.aic if hasattr(res,'aic') else np.inf
                if np.isfinite(aic) and aic < best_aic:
                    best_aic = aic; best_order=(p,D,q); best_model = res
            except Exception as e:
                # skip failing combos
                continue
    if best_model is None:
        print("  No ARIMA model converged for", comp, "- skipping.")
        continue
    print("  Best ARIMA order:", best_order, "AIC:", round(best_aic,2))

    # Forecast with best_model
    try:
        steps = len(test_series)
        pred = best_model.get_forecast(steps=steps)
        y_pred = pred.predicted_mean
        # align index: predicted mean has integer index starting at end of train_series; convert to test dates
        y_pred.index = test_series.index
    except Exception as e:
        # fallback: dynamic_forecast using append+predict
        try:
            y_pred = best_model.predict(start=test_series.index[0], end=test_series.index[-1])
        except Exception as e2:
            print("  Forecast failed for ARIMA on", comp, "-", e2)
            continue

    # Save ARIMA preds
    out_arima = pd.DataFrame({'date': y_pred.index, 'y_test': test_series.values, 'y_pred': y_pred.values})
    safe = safe_name(comp)
    arima_path = os.path.join(OUT_DIR, f"{safe}_ARIMA_preds.csv")
    out_arima.to_csv(arima_path, index=False)
    print("  Saved ARIMA preds ->", arima_path)

    # ARIMAX: if ESG dynamic (nunique>1) use ESG_lag1 as exog; else skip
    arimax_path = None
    if df['ESG_lag1'].notna().sum() > len(df)*0.01 and df['ESG_lag1'].nunique(dropna=True) > 1:
        # build exog aligned to return series
        exog = df.loc[ret_idx, 'ESG_lag1'].astype(float)
        exog_train = exog.iloc[train_idx]
        exog_test = exog.iloc[test_idx]
        # try same order as best ARIMA first, then grid if fails
        arimax_model = None
        tried = []
        orders_to_try = [best_order] + [(p,D,q) for p in P_GRID for q in Q_GRID]
        for order in orders_to_try:
            if order is None or order in tried:
                continue
            tried.append(order)
            try:
                mod = SARIMAX(train_series, exog=exog_train, order=order, enforce_stationarity=False, enforce_invertible=False)
                res = mod.fit(disp=False, maxiter=50)
                arimax_model = res
                break
            except Exception:
                continue
        if arimax_model is not None:
            try:
                pred = arimax_model.get_forecast(steps=len(exog_test), exog=exog_test)
                y_pred_x = pred.predicted_mean
                y_pred_x.index = test_series.index
                out_arimax = pd.DataFrame({'date': y_pred_x.index, 'y_test': test_series.values, 'y_pred': y_pred_x.values})
                arimax_path = os.path.join(OUT_DIR, f"{safe}_ARIMAX_preds.csv")
                out_arimax.to_csv(arimax_path, index=False)
                print("  Saved ARIMAX preds ->", arimax_path)
            except Exception as e:
                print("  ARIMAX forecasting failed for", comp, "-", e)
        else:
            print("  No ARIMAX model converged for", comp, "- skipping ARIMAX.")
    else:
        print("  ESG not time-varying enough for ARIMAX for", comp, "- skipping ARIMAX.")

    # record summary
    summary_records.append({
        'Company': comp,
        'ARIMA_path': arima_path,
        'ARIMAX_path': arimax_path,
        'ARIMA_order': str(best_order),
        'ARIMA_aic': best_aic
    })

# save summary
pd.DataFrame(summary_records).to_csv(os.path.join(OUT_DIR, "phase5_models_summary.csv"), index=False)
print("\nPhase5 finished. Summary saved to results/phase5/phase5_models_summary.csv")

# A2. Plot baseline forecasts vs actual
for sym, info in results_baseline.items():
    test = info['test']
    pred = info['pred']
    plt.figure(figsize=(12,4))
    plt.plot(test.index, test.values, label='Actual (test)')
    plt.plot(test.index, pred.values, label='ARIMA forecast')
    plt.title(f"{sym} — Baseline ARIMA forecast on returns")
    plt.legend()
    plt.show()

# B3. ARIMAX without trend (no intercept)
for sym, dfc in cleaned_data.items():
    print("\nTRY ARIMAX (no trend) for", sym)
    ret = dfc['return'].dropna()
    esg_vals = dfc['ESG'].dropna().unique()
    if len(esg_vals)==0:
        print("  no ESG -> skipping")
        continue
    exog_full = pd.Series(esg_vals[0], index=ret.index, name='ESG')
    pair = pd.concat([ret, exog_full], axis=1).dropna()
    if len(pair) < 300:
        print("  too few aligned obs -> skip")
        continue
    train_y, test_y = pair.iloc[:-252,0], pair.iloc[-252:,0]
    train_exog, test_exog = pair.iloc[:-252,1], pair.iloc[-252:,1]
    try:
        model = SARIMAX(train_y, exog=train_exog, order=(1,0,1), trend='n',
                        enforce_stationarity=False, enforce_invertibility=False)
        res = model.fit(disp=False)
        print("  Converged. AIC:", round(res.aic,2))
        pred = res.get_forecast(steps=len(test_y), exog=test_exog).predicted_mean
        print("  Eval:", evaluate_forecast(test_y, pred))
    except Exception as e:
        print("  Fit failed:", e)

# B4. Compare results
results_arimax = {}
comparison_rows = []

for sym in results_baseline.keys():
    base = results_baseline[sym]['eval']
    if sym in results_arimax:
        arx = results_arimax[sym]['eval']
        arx_note = results_arimax[sym].get('note', 'converged')
    else:
        arx = {'MAE': np.nan, 'RMSE': np.nan}
        arx_note = 'no_arimax'

    comparison_rows.append({
        'Symbol': sym,
        'ARIMA_MAE': round(base['MAE'], 6),
        'ARIMA_RMSE': round(base['RMSE'], 6),
        'ARIMAX_MAE': round(arx['MAE'], 6),
        'ARIMAX_RMSE': round(arx['RMSE'], 6),
        'ARIMAX_status': arx_note
    })

comparison_df = pd.DataFrame(comparison_rows).set_index('Symbol')
display(comparison_df)

# C5. Multivariate VAR (returns + volatility)
var_models = {}

for sym, dfc in cleaned_data.items():
    print("\n=== VAR model for", sym, "===")
    df_var = dfc[['return','volatility_7d']].dropna()

    if len(df_var) < 300:
        print("  Not enough data — skipping.")
        continue

    # Train-test split
    train = df_var.iloc[:-252]
    test  = df_var.iloc[-252:]

    # lag selection
    model = VAR(train)
    selected = model.select_order(maxlags=8)
    lag = selected.selected_orders.get('aic', selected.selected_orders.get('bic', 1))
    if lag is None:
        lag = 1

    print("  Selected lag:", lag)

    fitted = model.fit(lag)
    var_models[sym] = fitted

    print(fitted.summary())

# Impulse Response Functions (IRF)
for sym, model in var_models.items():
    print(f"\nIRF for {sym}")
    irf = model.irf(10)  # 10-day horizon
    irf.plot(orth=False)
    plt.suptitle(f"{sym} — VAR Impulse Response (10 days)")
    plt.show()

# Granger Causality Tests

granger_summary = {}

def granger_pvalues(g_test_result):
    """
    Extract p-values (F-test) from grangercausalitytests() output.
    Returns dict: {lag: pvalue}
    """
    pvals = {}
    for lag, tests in g_test_result.items():
        pvals[lag] = tests[0]['ssr_ftest'][1]   # [1] = p-value
    return pvals

for sym, model in var_models.items():
    print(f"\n=== Granger Causality for {sym} ===")

    # Get VAR endogenous data
    df = pd.DataFrame(model.model.endog, columns=['return','vol'])

    maxlag = 5  # adjust if needed

    # RETURN → VOL
    print("Return → Volatility")
    g1 = grangercausalitytests(df[['vol','return']], maxlag=maxlag, verbose=False)
    g1_pvalues = granger_pvalues(g1)
    print(pd.DataFrame.from_dict(g1_pvalues, orient='index', columns=['p_value']))

    # VOL → RETURN
    print("\nVolatility → Return")
    g2 = grangercausalitytests(df[['return','vol']], maxlag=maxlag, verbose=False)
    g2_pvalues = granger_pvalues(g2)
    print(pd.DataFrame.from_dict(g2_pvalues, orient='index', columns=['p_value']))

    granger_summary[sym] = {
        'return_to_vol': g1_pvalues,
        'vol_to_return': g2_pvalues
    }

"""### Phase 6: Deep Learning Modelling (LSTM)

Plan:
1. Convert each company's time-series into supervised training sequences (window → next-day return).
2. Normalize features using a `StandardScaler` fit on the training set only.
3. Split chronologically into Train / Validation / Test (test = last 252 business days).
4. Build a compact LSTM (1–2 layers) with a dense output predicting the next-day return.
5. Train with EarlyStopping on validation loss.
6. Save predictions, compute MAE and RMSE on the test set and compare with ARIMA / ARIMAX.

"""

# Configuration
import os, random, math
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
from pandas.tseries.offsets import BDay
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

WINDOW = 20               # number of past days used to predict next day
TEST_BUS_DAYS = 252       # test = last 252 business days (approx 1 trading year)
TRAIN_FRAC = 0.6          # 60% -> train, 40% -> validation
BATCH_SIZE = 32
EPOCHS = 80
PATIENCE = 8
LSTM_UNITS = 64
DROPOUT = 0.15
SEED = 42

# output folders
OUT_DIR = "results/phase6"
PRED_DIR = os.path.join(OUT_DIR, "preds")
PLOT_DIR = os.path.join(OUT_DIR, "plots")
os.makedirs(PRED_DIR, exist_ok=True)
os.makedirs(PLOT_DIR, exist_ok=True)

# reproducibility
np.random.seed(SEED)
tf.random.set_seed(SEED)
random.seed(SEED)
os.environ['PYTHONHASHSEED'] = str(SEED)

print("Phase 6 configuration loaded.")

# Safety Checks + Helper Functions

def safe_datetime_index(df):
    df = df.copy()
    try:
        df.index = pd.to_datetime(df.index)
    except:
        for col in df.columns:
            if 'date' in col.lower():
                try:
                    df.index = pd.to_datetime(df[col])
                    break
                except:
                    pass
    return df.sort_index()

def ensure_features(df, esg_value=np.nan):
    df = df.copy()
    df = safe_datetime_index(df)

    if 'log_price' not in df.columns and 'close' in df.columns:
        df['log_price'] = np.where(df['close'] > 0, np.log(df['close']), np.nan)

    if 'return' not in df.columns:
        if 'log_price' in df.columns:
            df['return'] = df['log_price'].diff()
        else:
            df['return'] = np.nan

    df['return_lag1'] = df['return'].shift(1)
    df['return_lag2'] = df['return'].shift(2)
    df['volatility_7d'] = df['return'].rolling(7).std()
    df['volatility_30d'] = df['return'].rolling(30).std()
    df['abs_return'] = df['return'].abs()

    if 'ESG' not in df.columns:
        df['ESG'] = esg_value

    return df

def build_sequences(df, feature_cols, target_col='return', window=WINDOW):
    df2 = df.dropna(subset=feature_cols + [target_col]).copy()
    if df2.shape[0] < window + 1:
        return None, None, None

    X, y, dates = [], [], []
    arr = df2[feature_cols].values
    target = df2[target_col].values
    idx = df2.index.to_list()

    for i in range(window, len(df2)):
        X.append(arr[i-window:i])
        y.append(target[i])
        dates.append(idx[i])

    if len(X) == 0:
        return None, None, None

    return np.stack(X), np.array(y), dates

def build_lstm_model(n_features):
    model = keras.Sequential([
        layers.Input(shape=(WINDOW, n_features)),
        layers.LSTM(LSTM_UNITS),
        layers.Dropout(DROPOUT),
        layers.Dense(32, activation='relu'),
        layers.Dense(1)
    ])
    model.compile(optimizer=keras.optimizers.Adam(1e-3), loss='mse')
    return model

def evaluate_basic(y_true, y_pred):
    y_true = np.asarray(y_true).ravel()
    y_pred = np.asarray(y_pred).ravel()
    mae = float(np.mean(np.abs(y_true - y_pred)))
    rmse = float(np.sqrt(np.mean((y_true - y_pred)**2)))
    mask = np.abs(y_true) > 1e-12
    mape = float(np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100) if mask.sum() > 0 else np.nan
    diracc = float(np.mean(np.sign(y_true) == np.sign(y_pred)))
    return {'MAE': mae, 'RMSE': rmse, 'MAPE(%)': mape, 'DirAcc': diracc}

print("Helpers loaded.")

# Normalize cleaned_data column names
import pandas as pd, numpy as np, traceback

if 'cleaned_data' not in globals():
    raise RuntimeError("cleaned_data not found. Run Phase 2 first.")

def normalize_colname(col):
    # If MultiIndex / tuple -> join with underscore
    if isinstance(col, tuple):
        return "_".join([str(x).strip() for x in col if x is not None])
    # if pandas Index or others, cast to str safely
    try:
        s = str(col)
    except Exception:
        s = repr(col)
    return s.strip()

fixed = {}
errors = {}
for comp, df in list(cleaned_data.items()):
    try:
        if not isinstance(df, pd.DataFrame):
            errors[comp] = f"not a DataFrame (type={type(df)})"
            continue
        # apply normalization
        new_cols = [normalize_colname(c) for c in df.columns]
        df2 = df.copy()
        df2.columns = new_cols
        # also ensure index is datetime if possible (non-destructive)
        try:
            df2.index = pd.to_datetime(df2.index)
        except Exception:
            pass
        cleaned_data[comp] = df2
        fixed[comp] = {"n_columns": len(new_cols)}
    except Exception as e:
        errors[comp] = str(e) + "\n" + traceback.format_exc()

print("Normalization complete.")
print("Fixed entries:", fixed)
if errors:
    print("\nErrors during normalization:")
    for k,v in errors.items():
        print("-", k, ":", v)

# Diagnostics after normalization
import pandas as pd, numpy as np

if 'selected_companies' not in globals():
    raise RuntimeError("selected_companies not found — load it (Phase 1 output).")

for comp in selected_companies:
    print("\n----", comp, "----")
    dfc = cleaned_data.get(comp)
    if dfc is None:
        print(" cleaned_data[comp] -> None")
        continue
    if not isinstance(dfc, pd.DataFrame):
        print(" cleaned_data[comp] is not a DataFrame; type =", type(dfc))
        continue
    print(" rows:", len(dfc))
    # show first 12 column names
    cols = list(dfc.columns)[:12]
    print(" first 12 columns:")
    for c in cols:
        print("  -", repr(c), " (type:", type(c).__name__, ")")
    # counts of likely columns
    for name in ['close','Close','log_price','return','return_lag1','volatility_7d','ESG']:
        if name in dfc.columns:
            print(f"  * has column {name} (non-null count = {int(dfc[name].notna().sum())})")
    # display 3 sample rows (first non-empty)
    with pd.option_context('display.max_columns', 40):
        try:
            display(dfc.head(3))
        except Exception as e:
            print("  Could not display samples:", e)

#  Build / fix features in cleaned_data for selected_companies
import numpy as np, pandas as pd
from pandas.tseries.offsets import BDay

WINDOW = 20  # keep consistent with Phase6
TEST_BUS_DAYS = 252

def find_col(df, substrs):
    """Return first column in df whose name contains any of substrs (case-insensitive)."""
    for c in df.columns:
        lc = c.lower()
        for s in substrs:
            if s.lower() in lc:
                return c
    return None

def ensure_company_features(df):
    """Take a DataFrame, create/normalize features in-place copy, and return it."""
    d = df.copy()
    # ensure string column names (fix tuple names if any)
    d.columns = [str(c) for c in d.columns]

    # ensure datetime index if possible
    try:
        d.index = pd.to_datetime(d.index)
    except Exception:
        # try common date columns
        date_col = find_col(d, ['date','update_date','timestamp','day'])
        if date_col:
            d.index = pd.to_datetime(d[date_col], errors='coerce')
    d = d.sort_index()

    # detect return / close / esg columns
    ret_col = find_col(d, ['return'])            # catches return, return_, returns...
    close_col = find_col(d, ['close','adj_close','price','last'])
    esg_col = find_col(d, ['esg','sustain','sustainalytics'])

    # If close exists, reindex to business days and forward-fill close so we can compute returns consistently
    if close_col:
        # reindex to business days from min->max and ffill close
        bidx = pd.date_range(d.index.min(), d.index.max(), freq=BDay())
        d = d.reindex(bidx)
        # coerce close to numeric then forward-fill
        d['close'] = pd.to_numeric(d[close_col], errors='coerce') if close_col != 'close' else pd.to_numeric(d['close'], errors='coerce')
        d['close'] = d['close'].ffill()
        # compute log_price and return freshly
        with np.errstate(divide='ignore', invalid='ignore'):
            d['log_price'] = np.where(d['close']>0, np.log(d['close']), np.nan)
        d['return'] = d['log_price'].diff()
    else:
        # no close: if return-like column exists, standardize name to 'return'
        if ret_col:
            d['return'] = pd.to_numeric(d[ret_col], errors='coerce')
        else:
            d['return'] = np.nan

    # Ensure ESG column exists (keep existing values if present)
    if esg_col:
        d['ESG'] = pd.to_numeric(d[esg_col], errors='coerce')
    else:
        # leave ESG as NaN (we won't invent values)
        d['ESG'] = d.get('ESG', np.nan)

    # fill ESG forward if it's monthly/quarterly (helps modeling); only forward-fill (no interpolation)
    if d['ESG'].notna().sum() > 0:
        d['ESG'] = d['ESG'].ffill().bfill()  # bfill as small safety in case first entries missing

    # engineered columns
    d['return_lag1'] = d['return'].shift(1)
    d['return_lag2'] = d['return'].shift(2)
    d['volatility_7d'] = d['return'].rolling(7, min_periods=1).std()
    d['volatility_30d'] = d['return'].rolling(30, min_periods=1).std()
    d['abs_return'] = d['return'].abs()

    # coerce numeric
    for col in ['log_price','return','return_lag1','return_lag2','volatility_7d','volatility_30d','abs_return','ESG']:
        if col in d.columns:
            d[col] = pd.to_numeric(d[col], errors='coerce')

    return d

# Apply to all selected companies (overwrites cleaned_data[comp] with enriched DataFrame)
prep_errors = {}
for comp in selected_companies:
    try:
        print("Processing features for:", comp)
        dfc = cleaned_data.get(comp)
        if dfc is None or not hasattr(dfc, 'columns'):
            raise ValueError("cleaned_data entry missing or invalid")
        df_new = ensure_company_features(dfc)
        cleaned_data[comp] = df_new
        # quick summary
        n_return = int(df_new['return'].notna().sum()) if 'return' in df_new.columns else 0
        n_esg = int(df_new['ESG'].notna().sum()) if 'ESG' in df_new.columns else 0
        print(f"  Rows: {len(df_new)} | non-null return: {n_return} | non-null ESG: {n_esg}")
    except Exception as e:
        prep_errors[comp] = str(e)
        print("  ERROR:", e)

print("\nFeature creation finished.")
if prep_errors:
    print("Errors:", prep_errors)

# Build sequences (train/val/test) into all_sequences dict
import numpy as np, pandas as pd
from pandas.tseries.offsets import BDay
import math

WINDOW = 20
TEST_BUS_DAYS = 252
TRAIN_FRAC = 0.60

all_sequences = {}
seq_errors = {}

def make_sequences_from_df(d, feature_cols, window=WINDOW):
    # drop rows missing any of the features or the target
    df2 = d.dropna(subset=feature_cols + ['return']).copy()
    if df2.shape[0] < window + 1:
        return None, None, None
    arr = df2[feature_cols].values
    tgt = df2['return'].values
    idx = df2.index.to_list()
    X, y, dates = [], [], []
    for i in range(window, len(df2)):
        X.append(arr[i-window:i])
        y.append(tgt[i])
        dates.append(idx[i])
    return np.stack(X), np.array(y), dates

for comp in selected_companies:
    try:
        print("\nPreparing sequences for:", comp)
        d = cleaned_data.get(comp)
        if d is None or not isinstance(d, pd.DataFrame):
            raise ValueError("missing cleaned_data entry")

        # choose features that exist
        feature_cols = [c for c in ['return_lag1','return_lag2','volatility_7d','volatility_30d','abs_return','ESG'] if c in d.columns]
        print("  Features chosen:", feature_cols)

        X, y, dates = make_sequences_from_df(d, feature_cols)
        if X is None:
            raise ValueError("no sequences produced (not enough non-missing rows)")

        # create test mask by date (target date >= last_date - TEST_BUS_DAYS)
        dates_idx = pd.to_datetime(dates)
        last_date = d.index.max()
        test_start = last_date - BDay(TEST_BUS_DAYS-1)
        test_mask = dates_idx >= pd.to_datetime(test_start)
        # fallback if too few test samples
        if test_mask.sum() < max(20, int(0.1*len(dates))):
            tsize = min(TEST_BUS_DAYS, len(dates))
            test_mask = np.arange(len(dates)) >= (len(dates) - tsize)

        idxs = np.arange(len(dates))
        test_idx = idxs[test_mask]
        pre_idx = idxs[~test_mask]
        if len(pre_idx) < 20:
            raise ValueError("insufficient pre-test samples for train/val split")

        n_pre = len(pre_idx)
        n_train = int(math.floor(TRAIN_FRAC * n_pre))
        train_idx = pre_idx[:n_train]
        val_idx   = pre_idx[n_train:]

        all_sequences[comp] = {
            'X_train': X[train_idx], 'y_train': y[train_idx],
            'X_val':   X[val_idx],   'y_val':   y[val_idx],
            'X_test':  X[test_idx],  'y_test':  y[test_idx],
            'feature_cols': feature_cols,
            'dates_test': [dates[i] for i in test_idx]
        }
        print(f"  sequences -> total:{len(dates)} train:{len(train_idx)} val:{len(val_idx)} test:{len(test_idx)}")

    except Exception as e:
        seq_errors[comp] = str(e)
        print("  ERROR:", e)

print("\nSequence preparation complete.")
if seq_errors:
    print("Errors:", seq_errors)
else:
    print("All selected companies prepared for modeling:", list(all_sequences.keys()))

# Train LSTM for each company in all_sequences
import numpy as np, os
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt

# training config (can be tuned)
BATCH_SIZE = 32
EPOCHS = 60
PATIENCE = 6
LSTM_UNITS = 64
DROPOUT = 0.15
SEED = 42

tf.random.set_seed(SEED); np.random.seed(SEED)

results = []
for comp, rec in all_sequences.items():
    try:
        print("\nTraining for:", comp)
        X_train, y_train = rec['X_train'], rec['y_train']
        X_val, y_val     = rec['X_val'], rec['y_val']
        X_test, y_test   = rec['X_test'], rec['y_test']
        dates_test = rec['dates_test']
        n_features = X_train.shape[2]

        # scale using train only
        scaler = StandardScaler()
        scaler.fit(X_train.reshape(-1, n_features))
        def scale(a): return scaler.transform(a.reshape(-1, n_features)).reshape(a.shape)
        X_train_s, X_val_s, X_test_s = scale(X_train), scale(X_val), scale(X_test)

        # build model
        model = keras.Sequential([
            layers.Input(shape=(WINDOW, n_features)),
            layers.LSTM(LSTM_UNITS),
            layers.Dropout(DROPOUT),
            layers.Dense(32, activation='relu'),
            layers.Dense(1)
        ])
        model.compile(optimizer='adam', loss='mse')

        cb = [keras.callbacks.EarlyStopping(monitor='val_loss', patience=PATIENCE, restore_best_weights=True)]
        history = model.fit(X_train_s, y_train, validation_data=(X_val_s, y_val),
                            epochs=EPOCHS, batch_size=BATCH_SIZE, callbacks=cb, verbose=1)

        # predict
        y_pred = model.predict(X_test_s, verbose=0).flatten()
        mae = float(mean_absolute_error(y_test, y_pred))
        rmse = float(np.sqrt(np.mean((y_test - y_pred)**2)))
        print(f"  Test MAE={mae:.6f}, RMSE={rmse:.6f}, n_test={len(y_test)}")

        # save CSV
        os.makedirs("results/phase6/preds", exist_ok=True)
        safe = comp.replace(' ','_').replace('/','_')
        out_df = pd.DataFrame({'date': pd.to_datetime(dates_test), 'y_test': y_test, 'y_pred': y_pred})
        out_df.to_csv(f"results/phase6/preds/{safe}_lstm_preds.csv", index=False)

        # plot
        plt.figure(figsize=(10,3))
        plt.plot(out_df['date'], out_df['y_test'], label='Actual')
        plt.plot(out_df['date'], out_df['y_pred'], label='Predicted')
        plt.title(comp + " Actual vs Predicted (LSTM)")
        plt.legend(); plt.tight_layout()
        plt.savefig(f"results/phase6/plots/{safe}_actual_vs_pred.png", dpi=150)
        plt.show()

        results.append({'Company': comp, 'MAE': mae, 'RMSE': rmse, 'n_test': len(y_test)})

    except Exception as e:
        print("  ERROR training", comp, "->", e)

# summary
if results:
    import pandas as pd
    print("\nPhase 6 LSTM results:")
    display(pd.DataFrame(results))
else:
    print("\nNo models trained (no prepared companies).")

"""### Phase 7:  Model evaluation

We compute the following evaluation metrics for each model and ticker:
- RMSE
- MAE
- MAPE
- Directional Accuracy (percent of days where predicted sign = actual sign)

We then assemble a comparison table, run a Diebold–Mariano (DM) test to compare the best classical model (ARIMA/ARIMAX) vs LSTM, and save plots (actual vs predicted) for each model and ticker.

"""

# Comparison: load classical preds + LSTM, compute metrics & DM
import os, glob, math
import numpy as np, pandas as pd
from sklearn.metrics import mean_absolute_error
from scipy import stats
import matplotlib.pyplot as plt

PHASE5_DIR = "results/phase5"
PHASE6_DIR = "results/phase6/preds"
OUT_DIR = "results/phase7"
PLOTS_DIR = os.path.join(OUT_DIR, "plots")
os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(PLOTS_DIR, exist_ok=True)

def rmse(a,b):
    a=np.asarray(a); b=np.asarray(b)
    return float(np.sqrt(np.mean((a-b)**2)))

def mape(a,b):
    a=np.asarray(a); b=np.asarray(b)
    mask = np.abs(a) > 1e-12
    return float(np.mean(np.abs((a[mask]-b[mask]) / a[mask]))*100) if mask.sum()>0 else np.nan

def dir_acc(a,b):
    a=np.asarray(a); b=np.asarray(b)
    return float(np.mean(np.sign(a) == np.sign(b)))

def dm_test(e1, e2):
    # squared error DM stat
    d = e1**2 - e2**2
    mean_d = d.mean(); sd = d.std(ddof=1); T = len(d)
    denom = sd/ math.sqrt(T) if sd>0 else np.nan
    dm = mean_d/denom if denom and denom>0 else np.nan
    p = 2*(1 - stats.norm.cdf(abs(dm))) if np.isfinite(dm) else np.nan
    return dm, p

companies = selected_companies.copy()

metrics = []
dm_results = []

for comp in companies:
    safe = comp.replace(" ","_").replace("/","_")
    print("\n--- Company:", comp, "---")
    # load LSTM preds if exists
    lstm_path = os.path.join(PHASE6_DIR, f"{safe}_lstm_preds.csv")
    lstm_df = None
    if os.path.exists(lstm_path):
        lstm_df = pd.read_csv(lstm_path, parse_dates=['date'])
        # ensure columns
        if 'y_test' not in lstm_df.columns:
            for c in lstm_df.columns:
                if 'actual' in c.lower() or 'y_' in c.lower():
                    lstm_df = lstm_df.rename(columns={c:'y_test'}); break
        if 'y_pred' not in lstm_df.columns:
            for c in lstm_df.columns:
                if 'pred' in c.lower(): lstm_df = lstm_df.rename(columns={c:'y_pred'}); break
        lstm_df = lstm_df[['date','y_test','y_pred']].dropna()
    else:
        print("  LSTM preds not found for", comp)

    # load ARIMA / ARIMAX preds
    arima_path = os.path.join(PHASE5_DIR, f"{safe}_ARIMA_preds.csv")
    arimax_path = os.path.join(PHASE5_DIR, f"{safe}_ARIMAX_preds.csv")
    arima_df = pd.read_csv(arima_path, parse_dates=['date']) if os.path.exists(arima_path) else None
    arimax_df = pd.read_csv(arimax_path, parse_dates=['date']) if os.path.exists(arimax_path) else None

    models_for_comp = {}
    if arima_df is not None:
        arima_df = arima_df.rename(columns={arima_df.columns[1]:'y_test', arima_df.columns[2]:'y_pred'})[['date','y_test','y_pred']].dropna()
        models_for_comp['ARIMA'] = arima_df
    if arimax_df is not None:
        arimax_df = arimax_df.rename(columns={arimax_df.columns[1]:'y_test', arimax_df.columns[2]:'y_pred'})[['date','y_test','y_pred']].dropna()
        models_for_comp['ARIMAX'] = arimax_df
    if lstm_df is not None:
        models_for_comp['LSTM'] = lstm_df

    if len(models_for_comp) == 0:
        print("  No model predictions available for", comp, " — skipping.")
        continue

    # Compute metrics for each model aligning on common dates per model (use each model's y_test)
    comp_metrics = []
    for mname, mdf in models_for_comp.items():
        y_true = mdf['y_test'].values
        y_pred = mdf['y_pred'].values
        if len(y_true) < 10:
            print("  Skipping", mname, " — too few points:", len(y_true))
            continue
        ma = mean_absolute_error(y_true, y_pred)
        rm = rmse(y_true, y_pred)
        mp = mape(y_true, y_pred)
        da = dir_acc(y_true, y_pred)
        comp_metrics.append({'Company': comp, 'Model': mname, 'MAE': ma, 'RMSE': rm, 'MAPE(%)': mp, 'DirAcc': da, 'n': len(y_true)})
        # save plot
        plt.figure(figsize=(10,3))
        plt.plot(mdf['date'], y_true, label='Actual', linewidth=1)
        plt.plot(mdf['date'], y_pred, label='Predicted', linewidth=1)
        plt.title(f"{comp} — {mname} Actual vs Predicted")
        plt.legend(); plt.tight_layout()
        plt.savefig(os.path.join(PLOTS_DIR, f"{safe}_{mname}_actual_vs_pred.png"), dpi=150)
        plt.close()

    # add these metrics
    for r in comp_metrics:
        metrics.append(r)

    # If we have both classical and LSTM, run DM between best classical (by RMSE) and LSTM
    classical = [r for r in comp_metrics if r['Model'] in ('ARIMA','ARIMAX')]
    lstm_row = next((r for r in comp_metrics if r['Model']=='LSTM'), None)
    if classical and lstm_row:
        best_class = min(classical, key=lambda x: x['RMSE'])
        # load arrays for DM: align dates between best_class and LSTM
        best_df = models_for_comp[best_class['Model']]
        lstm_df_local = models_for_comp['LSTM']
        merged = best_df.merge(lstm_df_local[['date','y_pred']], on='date', suffixes=('_class','_lstm'))
        merged = merged.dropna(subset=['y_test','y_pred_class','y_pred_lstm'])
        if merged.shape[0] >= 10:
            e_class = merged['y_test'].values - merged['y_pred_class'].values
            e_lstm = merged['y_test'].values - merged['y_pred_lstm'].values
            dm_stat, pval = dm_test(e_class, e_lstm)
            dm_results.append({'Company': comp, 'BestClassical': best_class['Model'], 'LSTM': 'LSTM',
                               'DM_stat': dm_stat, 'p_value': pval, 'n': merged.shape[0]})
            print(f"  DM test ({best_class['Model']} vs LSTM): stat={dm_stat:.4f}, p={pval:.4f}, n={merged.shape[0]}")
        else:
            dm_results.append({'Company': comp, 'BestClassical': best_class['Model'], 'LSTM': 'LSTM',
                               'DM_stat': np.nan, 'p_value': np.nan, 'n': merged.shape[0]})
            print("  Not enough overlapping dates for DM test (need >=10).")
    else:
        print("  DM test skipped (need both classical and LSTM predictions).")

# save outputs
metrics_df = pd.DataFrame(metrics)
dm_df = pd.DataFrame(dm_results)
metrics_df.to_csv(os.path.join(OUT_DIR, "comparison_metrics.csv"), index=False)
dm_df.to_csv(os.path.join(OUT_DIR, "comparison_dm.csv"), index=False)

print("\nComparison finished. Metrics saved to", os.path.join(OUT_DIR, "comparison_metrics.csv"))
print("DM results saved to", os.path.join(OUT_DIR, "comparison_dm.csv"))
print("Plots in", PLOTS_DIR)

# Comparison
import os, glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter

PHASE5_DIR = "results/phase5"
PHASE6_DIR = "results/phase6/preds"
OUT_PLOTS = "results/phase7/plots"
os.makedirs(OUT_PLOTS, exist_ok=True)

companies = selected_companies if 'selected_companies' in globals() else []
if not companies:
    files = glob.glob(os.path.join(PHASE6_DIR, "*_lstm_preds.csv"))
    companies = [os.path.basename(f).replace("_lstm_preds.csv","").replace("_"," ") for f in files]

def load_preds(path):
    if not os.path.exists(path):
        return None
    df = pd.read_csv(path, parse_dates=['date'])
    # normalize names heuristically
    cols = {c:c for c in df.columns}
    for c in df.columns:
        lc = c.lower()
        if 'pred' in lc and 'y_pred' not in cols:
            cols[c] = 'y_pred'
        if ('test' in lc or 'actual' in lc or 'y_' in lc) and 'y_test' not in cols:
            cols[c] = 'y_test'
    df = df.rename(columns=cols)
    if {'date','y_test','y_pred'}.issubset(set(df.columns)):
        return df[['date','y_test','y_pred']].sort_values('date')
    return df.sort_values('date')

for comp in companies:
    safe = comp.replace(" ","_").replace("/","_")
    print(f"\nProcessing: {comp}")

    lstm = load_preds(os.path.join(PHASE6_DIR, f"{safe}_lstm_preds.csv"))
    arimax = load_preds(os.path.join(PHASE5_DIR, f"{safe}_ARIMAX_preds.csv"))
    arima  = load_preds(os.path.join(PHASE5_DIR, f"{safe}_ARIMA_preds.csv"))

    # prefer ARIMAX if exists else ARIMA
    classical = arimax if arimax is not None and 'y_pred' in arimax.columns else arima
    classical_name = "ARIMAX" if (arimax is not None and 'y_pred' in arimax.columns) else "ARIMA"

    if lstm is None or 'y_pred' not in lstm.columns:
        print("  No LSTM preds found -> skip", comp); continue

    if classical is None or 'y_pred' not in classical.columns:
        print("  No classical preds found -> plotting Actual vs LSTM with bands")
        merged = lstm.dropna(subset=['y_test']).copy().sort_values('date')
        # residuals for LSTM on test window
        res_lstm = merged['y_test'] - merged['y_pred']
        sigma_lstm = res_lstm.std(ddof=1)
        merged['lstm_upper'] = merged['y_pred'] + sigma_lstm
        merged['lstm_lower'] = merged['y_pred'] - sigma_lstm

        # plot full
        plt.figure(figsize=(12,4))
        plt.plot(merged['date'], merged['y_test'], label='Actual', lw=1.2)
        plt.plot(merged['date'], merged['y_pred'], label='LSTM', lw=1)
        plt.fill_between(merged['date'], merged['lstm_lower'], merged['lstm_upper'], alpha=0.2, label='LSTM ±1σ')
        plt.title(f"{comp} — Actual vs LSTM (with ±1σ band)")
        plt.legend(); plt.grid(alpha=0.2)
        plt.gca().xaxis.set_major_formatter(DateFormatter('%Y-%m-%d')); plt.xticks(rotation=25)
        fname_full = os.path.join(OUT_PLOTS, f"{safe}_comparison_full_bands.png")
        plt.savefig(fname_full, dpi=150, bbox_inches='tight'); plt.show()

        # zoom last 60
        zoom = merged.tail(60)
        plt.figure(figsize=(12,3))
        plt.plot(zoom['date'], zoom['y_test'], label='Actual', lw=1.2)
        plt.plot(zoom['date'], zoom['y_pred'], label='LSTM', lw=1)
        plt.fill_between(zoom['date'], zoom['lstm_lower'], zoom['lstm_upper'], alpha=0.2)
        plt.title(f"{comp} — Zoom last 60 days (LSTM ±1σ)")
        plt.legend(); plt.grid(alpha=0.2)
        plt.gca().xaxis.set_major_formatter(DateFormatter('%Y-%m-%d')); plt.xticks(rotation=25)
        fname_zoom = os.path.join(OUT_PLOTS, f"{safe}_comparison_zoom60_bands.png")
        plt.savefig(fname_zoom, dpi=150, bbox_inches='tight'); plt.show()
        print("  Saved:", fname_full, fname_zoom)
        continue

    # merge classical & lstm
    dfc = classical.rename(columns={'y_test':'y_test_class','y_pred':'y_pred_class'})
    dfl = lstm.rename(columns={'y_test':'y_test_lstm','y_pred':'y_pred_lstm'})
    merged = dfc.merge(dfl, on='date', how='outer').sort_values('date')
    # choose target y_test (prefer classical's)
    merged['y_test'] = merged['y_test_class'].combine_first(merged['y_test_lstm'])
    merged = merged.dropna(subset=['y_test']).copy()
    merged = merged[ merged['y_pred_class'].notna() | merged['y_pred_lstm'].notna() ]

    # compute residual std on overlapping part (use rows where both preds exist to get comparable sigma)
    overlap = merged.dropna(subset=['y_pred_class','y_pred_lstm'])
    # residuals relative to y_test
    sigma_class = (overlap['y_test'] - overlap['y_pred_class']).std(ddof=1) if overlap.shape[0] > 5 else (merged['y_test'] - merged['y_pred_class']).std(ddof=1)
    sigma_lstm = (overlap['y_test'] - overlap['y_pred_lstm']).std(ddof=1) if overlap.shape[0] > 5 else (merged['y_test'] - merged['y_pred_lstm']).std(ddof=1)
    # fill bands
    merged['class_up'] = merged['y_pred_class'] + sigma_class
    merged['class_lo'] = merged['y_pred_class'] - sigma_class
    merged['lstm_up'] = merged['y_pred_lstm'] + sigma_lstm
    merged['lstm_lo'] = merged['y_pred_lstm'] - sigma_lstm

    # Full plot
    plt.figure(figsize=(12,4))
    plt.plot(merged['date'], merged['y_test'], label='Actual', lw=1.2)
    if merged['y_pred_class'].notna().any():
        plt.plot(merged['date'], merged['y_pred_class'], label=classical_name, lw=1)
        plt.fill_between(merged['date'], merged['class_lo'], merged['class_up'], alpha=0.18)
    if merged['y_pred_lstm'].notna().any():
        plt.plot(merged['date'], merged['y_pred_lstm'], label='LSTM', lw=1)
        plt.fill_between(merged['date'], merged['lstm_lo'], merged['lstm_up'], alpha=0.18)
    plt.title(f"{comp} — Actual vs {classical_name} vs LSTM (±1σ band)")
    plt.legend(); plt.grid(alpha=0.2)
    plt.gca().xaxis.set_major_formatter(DateFormatter('%Y-%m-%d')); plt.xticks(rotation=25)
    fname_full = os.path.join(OUT_PLOTS, f"{safe}_comparison_full_bands.png")
    plt.savefig(fname_full, dpi=150, bbox_inches='tight'); plt.show()

    # Zoom last 60 days
    zoom = merged.tail(60)
    plt.figure(figsize=(12,3))
    plt.plot(zoom['date'], zoom['y_test'], label='Actual', lw=1.2)
    if zoom['y_pred_class'].notna().any():
        plt.plot(zoom['date'], zoom['y_pred_class'], label=classical_name, lw=1)
        plt.fill_between(zoom['date'], zoom['class_lo'], zoom['class_up'], alpha=0.18)
    if zoom['y_pred_lstm'].notna().any():
        plt.plot(zoom['date'], zoom['y_pred_lstm'], label='LSTM', lw=1)
        plt.fill_between(zoom['date'], zoom['lstm_lo'], zoom['lstm_up'], alpha=0.18)
    plt.title(f"{comp} — Zoom last 60 days (±1σ bands)")
    plt.legend(); plt.grid(alpha=0.2)
    plt.gca().xaxis.set_major_formatter(DateFormatter('%Y-%m-%d')); plt.xticks(rotation=25)
    fname_zoom = os.path.join(OUT_PLOTS, f"{safe}_comparison_zoom60_bands.png")
    plt.savefig(fname_zoom, dpi=150, bbox_inches='tight'); plt.show()

    print("  Saved:", fname_full, fname_zoom)

print("\nDone — banded plots saved to:", OUT_PLOTS)

"""### Phase 8: Interpretation

This phase performs interpretation of ESG effects (to the extent possible with the current dataset), summarizes VAR impulse-response results, identifies which ESG components *could* improve forecasting (if time-varying components exist), and produces concise company-wise summaries.

Notes:
- The dataset contains a static ESG score (one value per company). Time-series causality with ESG is therefore not feasible unless you have time-varying ESG or create proxies (monthly revisions, event flags, news sentiment).
- The code below detects this automatically and falls back to cross-sectional tests or feature-selection methods where appropriate.

"""

# Phase 8 — Part 1 : Detect ESG variability & cross-sectional tests
import os, numpy as np, pandas as pd, matplotlib.pyplot as plt
from scipy import stats
from sklearn.linear_model import LinearRegression

OUT = "results/phase8"
os.makedirs(OUT, exist_ok=True)

# REQUIREMENTS: cleaned_data (dict company->DataFrame) and selected_companies list
if 'cleaned_data' not in globals() or 'selected_companies' not in globals():
    raise RuntimeError("Please run earlier phases to produce cleaned_data and selected_companies.")

# 1) Check ESG variability per company
esg_info = []
for comp in selected_companies:
    df = cleaned_data.get(comp)
    if df is None:
        esg_info.append({'Company':comp, 'n_obs':0, 'n_unique_ESG':0, 'is_timevarying':False})
        continue
    n_obs = len(df)
    if 'ESG' not in df.columns:
        n_unique = 0
    else:
        n_unique = int(df['ESG'].nunique(dropna=True))
    is_tv = (n_unique > 1)
    esg_info.append({'Company':comp, 'n_obs':n_obs, 'n_unique_ESG':n_unique, 'is_timevarying':is_tv})

esg_df = pd.DataFrame(esg_info)
esg_df.to_csv(os.path.join(OUT,"esg_variability_summary.csv"), index=False)
print("ESG variability summary:")
display(esg_df)

# 2) If ESG is static for ALL selected companies -> run cross-sectional tests
if not esg_df['is_timevarying'].any():
    print("\nESG is static for all selected companies -> running cross-sectional tests")
    cross = []
    for comp in selected_companies:
        df = cleaned_data.get(comp)
        if df is None or 'return' not in df.columns:
            cross.append({'Company':comp, 'mean_return':np.nan, 'vol_return':np.nan, 'ESG': np.nan})
            continue
        mean_r = float(df['return'].dropna().mean()) if df['return'].dropna().size>0 else np.nan
        vol_r = float(df['return'].dropna().std()) if df['return'].dropna().size>0 else np.nan
        esg_val = float(df['ESG'].dropna().mean()) if ('ESG' in df.columns and df['ESG'].dropna().size>0) else np.nan
        cross.append({'Company':comp, 'mean_return':mean_r, 'vol_return':vol_r, 'ESG':esg_val})
    cross_df = pd.DataFrame(cross).dropna(subset=['ESG'])
    cross_df.to_csv(os.path.join(OUT,"cross_section_esg_vs_returns.csv"), index=False)
    display(cross_df)

    # simple Pearson correlation
    if cross_df.shape[0] >= 3:
        r_mean, p_mean = stats.pearsonr(cross_df['ESG'], cross_df['mean_return'])
        r_vol, p_vol = stats.pearsonr(cross_df['ESG'], cross_df['vol_return'])
        print(f"\nCross-sectional Pearson: ESG vs mean return r={r_mean:.3f}, p={p_mean:.3f}")
        print(f"Cross-sectional Pearson: ESG vs vol(return) r={r_vol:.3f}, p={p_vol:.3f}")
    else:
        print("Not enough companies for robust cross-sectional correlation (need >=3).")
else:
    print("\nAt least one company has time-varying ESG -> skipping cross-sectional test fallback (will run time-series VAR/IRF below for those companies).")

# Save human-readable guidance
with open(os.path.join(OUT,"phase8_readme.txt"), "w") as f:
    f.write("Phase 8 outputs:\n- esg_variability_summary.csv\n- cross_section_esg_vs_returns.csv (if created)\n- VAR/IRF outputs (if ESG time-varying)\n- feature importance outputs\n")
print("\nSaved phase8 readme.")

# Phase 8 — Part 4 : Compose concise company-wise summaries (text) based on results above
import json
SUM_OUT = os.path.join(OUT, "company_summaries.txt")

summary_lines = []
for comp in selected_companies:
    summary_lines.append(f"--- {comp} ---")
    # ESG variability
    row = esg_df[esg_df['Company']==comp]
    if row.shape[0]==1:
        is_tv = bool(row['is_timevarying'].iloc[0])
        summary_lines.append(f"ESG time-varying: {is_tv} (unique_ESG={int(row['n_unique_ESG'].iloc[0])})")
    else:
        summary_lines.append("ESG time-varying: Unknown")

    # Cross-sectional result (if exists)
    csf = os.path.join(OUT,"cross_section_esg_vs_returns.csv")
    if os.path.exists(csf):
        csdf = pd.read_csv(csf)
        if comp in csdf['Company'].values:
            r = csdf[csdf['Company']==comp].iloc[0]
            summary_lines.append(f"Mean return (sample): {r['mean_return']:.6f}, vol(return): {r['vol_return']:.6f}, ESG: {r['ESG']:.3f}")

    # VAR IRF summary
    irf_file = os.path.join(OUT,"var_irf","irf_summaries.csv")
    if os.path.exists(irf_file):
        irf_df = pd.read_csv(irf_file)
        if comp in irf_df['Company'].values:
            r = irf_df[irf_df['Company']==comp].iloc[0]
            summary_lines.append(f"VAR lag p={int(r['lag_p'])}, peak |ESG->RET|={r['peak_abs_ESG->RET']:.4g}, peak |RET->ESG|={r['peak_abs_RET->ESG']:.4g}")

    # Feature importance
    fi_file = os.path.join(OUT,"feature_importance","feature_importances.csv")
    if os.path.exists(fi_file):
        fidf = pd.read_csv(fi_file)
        if comp in fidf['Company'].values:
            top = fidf[fidf['Company']==comp].sort_values('importance', ascending=False).head(5)
            tops = ", ".join([f"{r['feature']}({r['importance']:.2f})" for _,r in top.iterrows()])
            summary_lines.append("Top predictive features (RF): " + tops)

    # Final high-level sentence
    # If ESG static -> say cannot infer dynamic ESG effect
    if row.shape[0]==1 and not bool(row['is_timevarying'].iloc[0]):
        summary_lines.append("Interpretation: ESG in this dataset is essentially static for this company; therefore dynamic causal inference or time-series forecasting improvements using ESG are not supported by the data. Consider obtaining time-varying ESG or proxies (news sentiment, event flags).")
    else:
        summary_lines.append("Interpretation: Time-varying ESG exists; see VAR IRF and feature-importance results above for dynamic relationships.")

    summary_lines.append("")  # blank line

# save summary
with open(SUM_OUT, "w") as f:
    f.write("\n".join(summary_lines))

print("Company summaries written to", SUM_OUT)
print("\nSample:\n")
print("\n".join(summary_lines[:40]))

"""### Literature Comparison

Existing research generally agrees that ESG scores, as commonly published by rating agencies, move very slowly over time.  
Because these values are updated infrequently, they tend to capture long-term characteristics of a company rather than short-term shifts in market behaviour.  
Studies such as Fatemi et al. (2018) and Albuquerque et al. (2020) highlight that while ESG ratings are useful for understanding long-run firm quality or risk, they are not designed to explain day-to-day price movements.[2][3]

On the other hand, several papers show that *time-sensitive* ESG information—such as news coverage, controversy alerts, or real-time sentiment—can have a measurable impact on short-term market outcomes.  

Lins et al. (2017), for example, find that investor trust in a company’s ESG practices becomes especially important during crisis periods, when markets respond quickly to new information.[4]  

More recent work, like Pedersen et al. (2021), demonstrates that rapidly updated ESG signals can improve forecasting when used alongside financial data.[1]

Our results are consistent with this broader literature.  
Because the ESG values in our dataset were static, they did not provide any additional time-series structure that a forecasting model could learn from.  
As a result, models that incorporated ESG (such as ARIMAX) did not outperform the simpler ARIMA model, and the LSTM model also did not gain any advantage from ESG features.  
This outcome aligns with the general consensus that **short-horizon forecasting requires ESG inputs that change over time**, not fixed scores.

### Final Conclusion

This project set out to evaluate whether Environmental, Social and Governance (ESG) factors can improve the forecasting of stock price movements.  
Using a cleaned and engineered dataset of three representative companies drawn from low, medium, and high ESG score groups, we built and compared multiple forecasting models: classical ARIMA/ARIMAX models and a deep learning LSTM model.  
We also performed diagnostic tests (ADF/KPSS), VAR impulse-response analysis, feature-importance checks, and a Diebold–Mariano (DM) test to statistically compare model performance.

### Key Findings
1. **ESG data in the available dataset was static (one value per company)** and did not vary over time.  
   Because of this, ESG did not contribute dynamic information that could be used for causality analysis, VAR modelling, or time-series-based improvements in forecasting performance.

2. **Across all companies, returns behaved as expected for financial data:**  
   - Highly noisy  
   - Weak autocorrelation  
   - Stationary after log-return transformation  
   These characteristics make forecasting inherently challenging and often limit the advantage of complex models.

3. **Model comparison results were mixed but informative:**  
   - For **C.H. Robinson (CHRW)**, ARIMA significantly outperformed LSTM  
     (DM test p = 0.0057), indicating that classical linear models captured short-term return structure better than deep learning for this series.  
   - For **Steel Partners (SPLP)** and **Highway Holdings (HIHO)**, the DM test showed **no statistically significant difference** between ARIMA and LSTM, meaning both models performed similarly.

4. **LSTM did not consistently outperform ARIMA**, which aligns with financial literature showing that deep learning models often require richer, higher-frequency, or more informative features to gain an advantage in short-horizon return forecasting.

5. **ESG showed no measurable forecasting value in this dataset**, not because ESG has no impact in reality, but because **a static, one-time ESG score cannot create predictive time-series structure**.  
   Time-varying ESG data (e.g., monthly/quarterly ESG ratings, controversies, governance changes, sentiment-based ESG proxies) would be necessary to identify dynamic ESG–return relationships.

### Overall Conclusion
The study concludes that **ESG did not enhance stock-return forecasting in the current dataset**, and classical ARIMA models performed as well as or better than deep learning models such as LSTM.  
The absence of time-varying ESG signals limits the capacity of models like ARIMAX, VAR, and LSTM to learn ESG-driven patterns.  
Nevertheless, the project successfully demonstrates a full forecasting workflow—data cleaning, feature engineering, model building, evaluation, and statistical comparison—with clear evidence of when and why each model performs best.

### Recommendations for Future Work
- Use **time-stamped ESG datasets** (e.g., monthly MSCI ESG revisions, Sustainalytics risk score updates, controversy/event data).  
- Incorporate **news-derived ESG sentiment**, which changes daily and can provide true predictive signals.  
- Evaluate multi-step or probabilistic forecasting frameworks (GARCH, Prophet, Transformers).  
- Extend analysis to larger cross-sections of companies to study ESG–return relationships more broadly.

### Final Note
Although the ESG scores did not improve forecasting accuracy in this dataset, the project provides a valuable methodological framework and highlights the importance of choosing data that matches the research question.  
The modelling and statistical comparison pipeline is fully functional and can be directly extended to richer ESG datasets in the future.

### References

[1] Pedersen, L. H., Fitzgibbons, S., & Pomorski, L. (2021). Responsible investing: The ESG-efficient frontier. *Journal of Financial Economics*, 142(2), 572–597.

[2] Albuquerque, R., Koskinen, Y., & Zhang, C. (2020). Corporate social responsibility and firm risk: Theory and empirical evidence. *Management Science*, 66(10), 4451–4470.

[3] Fatemi, A., Glaum, M., & Kaiser, S. (2018). ESG performance and firm value: The moderating role of disclosure. *Global Finance Journal*, 38, 45–64.

[4] Lins, K. V., Servaes, H., & Tamayo, A. (2017). Social capital, trust, and firm performance: The value of corporate social responsibility during the financial crisis. *The Journal of Finance*, 72(4), 1785–1824.
"""